; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 	
	wollewald/ADS1220_WE @ 1.0.15
	br3ttb/PID @ 1.2.1
	tobiasschuerg/ESP8266 Influxdb @ 3.13.1
	me-no-dev/AsyncTCP @ 1.1.1
	https://github.com/me-no-dev/ESPAsyncWebServer.git ; would prefer specific version
	bblanchon/ArduinoJson@6.21.4

build_flags = 
	-I./src
	-std=gnu++17
	-DCORE_DEBUG_LEVEL=3	

build_unflags = 
	-std=gnu++11